---
dependencies: []

galaxy_info:
  author: chrisley75
  description: Kibana for Linux.
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Debian
      versions:
        - jessie
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
  galaxy_tags:
    - web
    - system
    - monitoring
    - kibana
    - elk
    - efk
    - logging
    - dataviz
