---
filebeat_version: 7.x
filebeat_create_config: true

filebeat_inputs:
  - type: log
    enabled: true
    paths:
      - "/var/log/httpd/ssl_access_log"
    document_type: chrisley_httpd
    tags: ["sslaccess", "httpd"]
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - "/var/log/httpd/ssl_error_log"
    document_type: chrisley_httpd
    tags: ["sslerror", "httpd"]
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - "/var/log/messages"
    document_type: syslog
    tags: ["syslogmessages", "kernel"]
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - "/var/log/yum.log"
    document_type: log
    tags: ["yummessages", "yum"]
    fields_under_root: true

filebeat_output_elasticsearch_enabled: false
filebeat_output_elasticsearch_hosts:
  - "elkaz.chrisley.fr:9200"

filebeat_output_logstash_enabled: true
filebeat_output_logstash_hosts:
  - "elkaz.chrisley.fr:5044"

filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log

filebeat_ssl_dir: /etc/pki/logstash
filebeat_ssl_certificate_file: ""
filebeat_ssl_key_file: ""
filebeat_ssl_insecure: "false"
