# roles/wordpress/tasks/install.yml
---

- name: 'Execute the command in remote shell to install php7.2 with amazon repository; stdout goes to the specified file on the remote.'
  shell: 'amazon-linux-extras install php7.2 -y >> /var/log/amazon-php72-log.txt'
  tags: php72

- name: Wait until the lock file is removed
  wait_for:
    path: /var/run/yum.pid
    state: absent

- name: Ensure repository is installed
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ wordpress_repository }}"
  tags: wordpress

- name: Wait until the lock file is removed
  wait_for:
    path: /var/run/yum.pid
    state: absent

- name: Ensure PHP7 and it's modules are installed
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ wordpress_packages }}"
  tags: wordpress

- name: Wait until the lock file is removed
  wait_for:
    path: /var/run/yum.pid
    state: absent

- name: Check whether Apache is already installed
  stat:
    path: "{{ wordpress_httpd_service }}"
  register: wordpress_httpd_status
  failed_when: not wordpress_httpd_status.stat.exists
  tags: wordpress

- name: Wait until the lock file is removed
  wait_for:
    path: /var/run/yum.pid
    state: absent

- name: Downloading Wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/latest.tar.gz

- name: Wait until the lock file is removed
  wait_for:
    path: /var/run/yum.pid
    state: absent

- name: Unpacking Wordpress from latest tarball
  unarchive:
    src: /tmp/latest.tar.gz
    dest: /var/www/
    remote_src: yes
  register: new_wp   

- name: Wait until the lock file is removed
  wait_for:
    path: /var/run/yum.pid
    state: absent

- name: Moving Wordpress files into www root
  synchronize:
    src: /var/www/wordpress/
    dest: /var/www/html
  delegate_to: "{{ inventory_hostname }}"
  when: new_wp.changed

- name: Wait until the lock file is removed
  wait_for:
    path: /var/run/yum.pid
    state: absent
