---
dependencies: []

galaxy_info:
  author: chrisley75
  description: Filebeat for Linux.
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - web
    - system
    - monitoring
    - elasticsearch
    - logging
    - filebeat
