---
dependencies: []

galaxy_info:
  author: chrisley75
  description: Logstash for Linux.
  license: "license (BSD, MIT)"
  min_ansible_version: 1.8
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - web
    - system
    - monitoring
    - logging
    - logs
    - elk
    - logstash
