# roles/wordpress/vars/main.yml
---

wordpress_repository:
  - epel-release

wordpress_packages:
  - https://centos7.iuscommunity.org/ius-release.rpm
  - php72u
  - mod_php72u
  - php72u-pdo
  - php72u-gd
  - php72u-common
  - php72u-json
  - php72u-cli
  - php72u-imap
  - php72u-pecl-apcu
  - php72u-xml
  - php72u-mysqlnd
  - php72u-pecl-imagick
  - php72u-ldap
  - php72u-opcache
  - unzip

wordpress_directory: '/var/www/html/'
wordpress_httpd_configuration: '/etc/httpd/conf.d/wordpress.conf'
wordpress_configuration: '/var/www/html/wp-config.php'
wordpress_plugin_directory: "{{ wordpress_directory }}/wp-content/plugins"
wordpress_theme_directory: "{{ wordpress_directory }}/wp-content/themes"
wordpress_httpd_service: '/usr/lib/systemd/system/httpd.service'

