---
galaxy_info:
  author: Robert de Bock
  role_name: httpd
  description: Install and configure httpd on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.6

  platforms:
    - name: Alpine
      versions:
        - all
    - name: ArchLinux
      version:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      version:
        - 7
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - artful
        - bionic

  galaxy_tags:
    - webserver
    - apache
    - httpd
    - installer
    - package
    - alpine
    - centos
    - debian
    - fedora
    - rhel
    - ubuntu

dependencies: []
