- name: "Install and configure Metricbeat to AZURE"
#  hosts: www.chrisley.fr
  hosts: "{{ target | default('nothing') }}"
  roles:
    - az-chrisley.metricbeat 
  vars:
    ansible_user: ec2-user
  become: true
