---
- name: Install metricbeat from Debian package
  apt:
    deb: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ elk_version }}-amd64.deb"
  become: yes

- name: Copy metricbeat configuration
  template:
    src: metricbeat.yml.j2
    dest: "/etc/metricbeat/metricbeat.yml"
    owner: root
    mode: 0600
  become: yes
  notify:

- name: Enable metricbeat service
  service:
    name: metricbeat
    state: started
    enabled: yes
  become: yes

- name: Set configuration dir
  set_fact:
    metricbeat_config_dir: "/etc/metricbeat"